name: CI

on:
    - push

jobs:
    ci:
        name: Test
        runs-on: ubuntu-latest
        steps:
            - name: Checkout the current repository
              uses: actions/checkout@v2
              with:
                  fetch-depth: 0
            - name: Setup NodeJS 16
              uses: actions/setup-node@v2
              with:
                  node-version: 16
            - name: Configure Node and npm
              run: npm set-script prepare ''
            - name: Install pnpm
              run: npm run ci:pnpm
            - name: Install dependencies
              run: pnpm ci:prod
            - name: Run Tests
              run: pnpm test
              env:
                  CI: true
