name: 'Issue States'

on:
    project_card:
        types: [created, edited, moved]

permissions:
    repository-projects: read
    issues: write
    pull-requests: write

jobs:
    state:
        name: 'Change state based on column'
        runs-on: ubuntu-latest
        steps:
            - name: 'Run the issue-states action'
              uses: dessant/issue-states@v2
              with:
                  github-token: ${{ secrets.bot }}
                  open-issue-columns: 'To do, In progress, Ready for review, Review in progress, Reviewer approved'
                  closed-issue-columns: 'Done'
